### PR TITLE
Minor change to re enable Compare mode and added POSMATCH control option.

### PR DESCRIPTION
**Pull request by mjs513**
@PaulStoffregen 
In a continuation of improving the QuadEncoder library @joepasquariello suggested a couple of additional changes.
1.  Add a flag for what POSMATCH will do when counters match the specified value, see page 3169 OUTCTL for bit
2.  changed name of the function call to reenable the Compare interrupt from resetCompareInterrupt to enableCompareInterrupt 

Hopefully this is the last change.  Other than these changes all seems to be working with the library.

### CODE REVIEW

**Comment by joepasquariello** [comment]
Mike,

Thanks. The only other suggestion I had was to add a function to modify positionCompareValue, similar to write(), which modifies initial (current) position. I think that’s something a user is likely to want if the are using compare interrupts.

Joe

**Comment by mjs513** [comment]
Thanks Paul.  Will get that incorporated either tonight or tomorrow.  But definitely good idea.

**Comment by mjs513** [comment]
@PaulStoffregen 
Went ahead and added a setCompareValue function to the library - update and tested the example QuadEncoder.ino sketch as well to demo it.

Got board so I went ahead and updated it now.

**Comment by joepasquariello** [comment]
Looks good, Mike. Did some testing of new flag and functions and all
    works as expected.
    
    Joe
    
    On 12/25/2021 1:43 PM, Mike S wrote:
    
    
      
      @PaulStoffregen
        Went ahead and added a setCompareValue function to the library -
        update and tested the example QuadEncoder.ino sketch as well to
        demo it.
      Got board so I went ahead and updated it now.
      —
        Reply to this email directly, view it on GitHub, or unsubscribe.
        Triage notifications on the go with GitHub Mobile for iOS or Android.
        
        You are receiving this because you were mentioned.Message
          ID: ***@***.***>
      [
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/PaulStoffregen/Teensy-4.x-Quad-Encoder-Library/pull/3#issuecomment-1001074804",
"url": "https://github.com/PaulStoffregen/Teensy-4.x-Quad-Encoder-Library/pull/3#issuecomment-1001074804",
"name": "View Pull Request"
},
"description": "View this Pull Request on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by PaulStoffregen** [comment]
Should I pull this in for 1.57-beta2 ?

**Comment by mjs513** [comment]
Yes please was going to post on the beta1 about the update but got sidetracked, which is inevitable.  Was wondering about the this in audio as well: https://github.com/PaulStoffregen/Audio/pull/419,  pr is only for wav and raw files nothing else.

**Pull request merged**
